### ISSUE TITLE
Improve stacktrace

### ISSUE THREAD

**Issue by Casperhr** [nodes-vapor/bugsnag#1]
![image](https://cloud.githubusercontent.com/assets/1279756/20647949/df454f82-b499-11e6-9e3d-ea45032f9410.png)

**Comment by Casperhr** [comment]
https://mikeash.com/pyblog/friday-qa-2014-08-15-swift-name-mangling.html

**Comment by Casperhr** [comment]
https://cocoawithlove.com/blog/2016/02/28/stack-traces-in-swift.html

**Comment by Casperhr** [comment]
@BrettRToomey knows something about this subject!

**Comment by steffendsommer** [comment]
Currently missing:

- [x] Cleaning up the stack trace by removing all the unnecessary characters.
- [x] A pointer hack to be able to skip all of the middlewares in the stacktrace (this would require a custom error type - e.g. AbortExtended).

**Comment by BrettRToomey** [comment]
Jobs done.
