### ISSUE TITLE
Fix Linux breaking due to Thread.callStackSymbols call

### ISSUE THREAD

**Issue by steffendsommer** [nodes-vapor/bugsnag#10]
On line 27 in `ConnectionManager.swift` we call `Thread.callStackSymbols` which will break on Linux. We need to look into how/if we can get the stack trace working on Linux.

**Comment by steffendsommer** [comment]
Some more information can be found here: https://github.com/apple/swift-corelibs-foundation/blob/master/Docs/Status.md

**Comment by BrettRToomey** [comment]
`Thread.callStackSymbols` is [NSUnimplemented](https://github.com/apple/swift-corelibs-foundation/blob/b5e006c3edb9b8ba410e3bf320acb6876db18c0f/Foundation/NSThread.swift#L254)

As far as I can tell, it's possible to do all of this in C so I'll look at writing a package for it and then adding it as a dependency here. On top of that, I'll have to look at demangling the Swift calls.

**Comment by steffendsommer** [comment]
Fixed with https://github.com/nodes-vapor/bugsnag/releases/tag/0.2.0
