### ISSUE TITLE
Add support for release

### ISSUE THREAD

**Issue by steffendsommer** [nodes-vapor/bugsnag#47]
Figure out if we could set e.g. the git hash as the release

**Comment by siemensikkema** [comment]
@steffendsommer how would we get the git hash?

**Comment by steffendsommer** [comment]
@siemensikkema unfortunately not possible with Vapor Cloud 1. Hopefully Vapor RED/Vapor Cloud 2 can support this. I would expect the hash to be available through an env. variable.

**Comment by siemensikkema** [comment]
Once that becomes possible, we could use the metadata property by just adding a value for the key "githash" or something. I don't think we need to bake it into Bugsnag. What are your thoughts on that?

**Comment by steffendsommer** [comment]
I quickly looked at the Bugsnag API reference and it seems like the version doesn't get pulled out of the metadata object: https://bugsnagerrorreportingapi.docs.apiary.io/#reference/0/notify/send-error-reports

It seems to go into the `app` object

**Comment by siemensikkema** [comment]
How about https://github.com/nodes-vapor/bugsnag/pull/59?

**Comment by steffendsommer** [comment]
Yes, that should do it 👍
