### ISSUE TITLE
Support for excluding specific errors

### ISSUE THREAD

**Issue by steffendsommer** [nodes-vapor/bugsnag#49]
Consider introducing a way to exclude specific errors being thrown by the Bugsnag middleware. One approach could be to allow closures being passed in where the closured takes in `Error` and returns a `Bool` to indicate if that specific error should be thrown or not. Then the consumer of the package could easily adjust it to fit their needs.

**Comment by BrettRToomey** [comment]
Would probably want this and another bugsnag error protocol that errors can conform to and provide this information

**Comment by siemensikkema** [comment]
@steffendsommer Implemented by https://github.com/nodes-vapor/bugsnag/pull/58. Will close this after that is merged.
