### ISSUE TITLE
New error protocol

### ISSUE THREAD

**Issue by Casperhr** [nodes-vapor/bugsnag#7]
enum MyError: AbortError {
    case missingUsername(metadata: Node?)
    case missingEmail(metadata: Node?)

    var code: Int {
        switch self {
            case .missingUsername: return 401
            case .missingEmail: return 402
        }
    }

    var status: Status {
        return .badRequest
    }

    var message: String {
        switch self {
            case .missingUsername: return "Missing username"
            case .missingEmail: return "Missing email"
        }
    }

    var metadata: Node? {
        switch self {
            case missingUsername(metadata: let node): return node
            case missingEmail(metadata: let node): return node
        }
    }
}

**Comment by Casperhr** [comment]
Or if you don't want a different default case for each one you could instead do something like:

```enum MyError: AbortError {
    case error(message: String, code: Int, status: Status, metadata: Node?)
}
```

Then for each of the values required for the protocol just extracted the associated values within the enum and return them

[9:32]  
The main downside of that is if you want to call the same error multiple times you now have to copy paste all of those values

[9:32]  
Instead of updating them in one place

**Comment by steffendsommer** [comment]
Fixed in https://github.com/nodes-vapor/bugsnag/releases/tag/0.1.2
